<style>
    footer {
        position: relative;
        left: 0;
        bottom: 0;
        width: 100%;
        margin-bottom: -200px;
        background-color: black;
        color: white;
        text-align: center;
        font-size: 17px;
        margin-top: 20px;
    }
</style>
<footer class="footer">
    <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/map.js"></script>
</body>
</html>