<!--<html lang="en">-->
<!--<head>-->
    <!-- Required meta tags -->
<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
<!---->
<!--    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">-->
<!---->
    <!--        Animate.css-->
<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">-->
<!---->
    <!-- Google JQuery CDN -->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!---->
<!---->
<!--<body>-->
<!--<div>-->
<!--    <div class="panel shadow1">-->
<!--        <form class="login-form" method="post" action="/loginPage.php">-->
<!--            <div class="panel-switch animated fadeIn">-->
<!--                <button type="submit" id="sign_up" class="">Sign Up</button>-->
<!--                <button type="submit" id="log_in" class="active-button">Log in</button>-->
<!--            </div>-->
<!--            <h1 class="animated fadeInUp animate1" id="title-login">Welcome Back !</h1>-->
<!--            <h1 class="animated fadeInUp animate1 hidden" id="title-signup">Welcome !</h1>-->
<!--            <fieldset id="login-fieldset" class="hidden">-->
<!--                <input class="login animated fadeInUp animate2" name="username" type="text"  required   placeholder="Username" value="" >-->
<!--                <input class="login animated fadeInUp animate3" name="password" type="password" required placeholder="Password" value="">-->
<!--            </fieldset>-->
<!--            <fieldset id="signup-fieldset">-->
<!--                <input class="login animated fadeInUp animate2" name="name" type="text"  required   placeholder="Name" value="" >-->
<!--                <input class="login animated fadeInUp animate2" name="username" type="text"  required   placeholder="Username" value="" >-->
<!--                <input class="login animated fadeInUp animate2" name="email" type="text"  required   placeholder="Email" value="" >-->
<!--                <input class="login animated fadeInUp animate3" name="password" type="password" placeholder="Choose password"  required  value="">-->
<!--            </fieldset>-->
<!--            <input type="submit" id="login-form-submit" class="login_form button animated fadeInUp animate4" value="Log in" name="loginBtn">-->
<!--            <input type="submit" id="signup-form-submit" class="login_form button animated fadeInUp animate4 hidden" value="Sign up" name="signupBtn">-->
            <!--            <p><a id="lost-password-link" href="" class="animated fadeIn animate5">I forgot my  login or password (!)</a></p>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->
<!--<style>-->
<!--    * {-->
<!--        margin: 0 auto;-->
<!--        padding: 0;-->
<!--    }-->
<!---->
<!--    html{-->
<!--        width: 100%;-->
<!--        height: 100vh;-->
<!--    }-->
<!---->
<!--    body {-->
<!--        /*background: #e5e5e5;*/-->
<!--        background-image: linear-gradient(-225deg, #E3FDF5 0%, #003366 100%);-->
<!--        background-image: linear-gradient(to top, #a8edea 0%, #003366 100%);-->
<!--        background-attachment: fixed;-->
<!--        background-repeat: no-repeat;-->
<!--        opacity: .95;-->
<!--        width: 100%;-->
<!--        text-align: center;-->
<!--        font-family: 'Open Sans', sans-serif;-->
<!--        font-weight: 600;-->
<!--        letter-spacing: 1px;-->
<!--        height: auto;-->
<!--    }-->
<!---->
<!--    .panel{-->
<!--        width: 300px;-->
<!--        max-width: 90%;-->
<!--        height: auto;-->
<!--        background:url('https://picsum.photos/1000/1500?image=827')  #FFFFFF;-->
<!--        background-repeat:no-repeat;-->
<!--        background-position: top center;-->
<!--        background-size: cover;-->
<!--        margin:5% auto 0px;-->
<!--    }-->
<!---->
<!---->
<!---->
<!---->
<!--    .shadow1{-->
<!--        -webkit-box-shadow:  0 20px 15px -15px rgba(119, 119, 119, 0.85);-->
<!--        -moz-box-shadow:  0 20px 15px -15px rgba(119, 119, 119, 0.85);-->
<!--        box-shadow:  0 40px 30px -30px rgba(119, 119, 119, 0.85);-->
<!--    }-->
<!---->
<!---->
<!--    form{-->
<!--        height: 500px;-->
<!--        padding: 50px;-->
<!--    }-->
<!---->
<!--    .panel-switch{-->
<!--        text-align: center;-->
<!--        margin-top: 30px;-->
<!--    }-->
<!---->
<!--    .panel-switch button{-->
<!--        display: inline-block;-->
<!--        width: 100px;-->
<!--        height: 40px;-->
<!--        background: #f03699;-->
<!--        margin: 0px 10px 50px;-->
<!--        border: none;-->
<!--        color: #fff;-->
<!--        font-family: 'Open Sans', sans-serif;-->
<!--        text-transform: uppercase;-->
<!--        font-weight: 600;-->
<!--        letter-spacing: 2px;-->
<!--        font-size: 0.8em;-->
<!---->
<!--        transition: background-color 0.2s , color:0.2s , opacity:0.2s;-->
<!--    }-->
<!---->
<!--    .panel-switch button:active{-->
<!--        background: #b52773;-->
<!--        color: #c9c9c9;-->
<!--    }-->
<!---->
<!--    .active-button{-->
<!--        opacity: 0.5;-->
<!--    }-->
<!---->
<!--    button , .button , a {-->
<!--        cursor: pointer;-->
<!--    }-->
<!---->
<!--    form h1{-->
<!--        color: #fff;-->
<!--        font-family: 'Open Sans', sans-serif;-->
<!--        text-transform: uppercase;-->
<!--        font-weight: 600;-->
<!--        letter-spacing: 4px;-->
<!--        margin: 50px 0;-->
<!--        font-size: 1.7em;-->
<!--    }-->
<!---->
<!--    fieldset{-->
<!--        border: none;-->
<!--    }-->
<!---->
<!--    .animate1 , .animate2 , .animate3 , .animate4{-->
<!--        -webkit-animation-duration: 2s;-->
<!--        -moz-animation-duration: 2s;-->
<!--    }-->
<!---->
<!--    .animate1-->
<!--    {-->
<!--        -webkit-animation-delay: 0.2s;-->
<!--        -moz-animation-delay: 0.2s;-->
<!--    }-->
<!---->
<!--    .animate2-->
<!--    {-->
<!--        -webkit-animation-delay: 0.7s;-->
<!--        -moz-animation-delay: 0.7s;-->
<!--    }-->
<!---->
<!--    .animate3-->
<!--    {-->
<!--        -webkit-animation-delay: 1.1s;-->
<!--        -moz-animation-delay: 1.1s;-->
<!--    }-->
<!---->
<!--    .animate4-->
<!--    {-->
<!--        -webkit-animation-delay: 1.5s;-->
<!--        -moz-animation-delay: 1.5s;-->
<!--    }-->
<!---->
<!--    .animate5-->
<!--    {-->
<!--        -webkit-animation-delay: 2.2s;-->
<!--        -moz-animation-delay: 2.2s;-->
<!--    }-->
<!---->
<!--    @-webkit-keyframes fadeInUp {-->
<!--        from {-->
<!--            opacity: 0;-->
<!--            -webkit-transform: translate3d(0, 100%, 0);-->
<!--            transform: translate3d(0, 100%, 0);-->
<!--        }-->
<!---->
<!--        to {-->
<!--            opacity: 1;-->
<!--            -webkit-transform: translate3d(0, 0, 0);-->
<!--            transform: translate3d(0, 0, 0);-->
<!--        }-->
<!--    }-->
<!---->
<!--    @keyframes fadeInUp {-->
<!--        from {-->
<!--            opacity: 0;-->
<!--            -webkit-transform: translate3d(0, 100%, 0);-->
<!--            transform: translate3d(0, 100%, 0);-->
<!--        }-->
<!---->
<!--        to {-->
<!--            opacity: 1;-->
<!--            -webkit-transform: translate3d(0, 0, 0);-->
<!--            transform: translate3d(0, 0, 0);-->
<!--        }-->
<!--    }-->
<!---->
<!--    fieldset input{-->
<!--        background: rgba(255, 255, 255, 0.2);-->
<!--        border: none;-->
<!--        border-radius: 5em;-->
<!--        height: 20px;-->
<!--        width: 80%;-->
<!--        margin: 10px 0;-->
<!--        padding: 5px;-->
<!--        text-indent: 10px;-->
<!--        color: #fff;-->
<!--        font-weight: 600;-->
<!--    }-->
<!---->
<!--    fieldset input::placeholder {-->
<!--        color: #c7c6c6;-->
<!--    }-->
<!---->
<!---->
<!--    fieldset input:focus {-->
<!--        outline:;-->
<!--        border: 1px solid rgba(0, 0, 0, 0.2);-->
<!--        border-radius: 5em;-->
<!--        margin: 9px 0;-->
<!--    }-->
<!---->
<!--    .login_form{-->
<!--        position: relative;-->
<!--        bottom:0;-->
<!--        width: 70%;-->
<!--        height: 4em;-->
<!--        margin-top: 50px;-->
<!--        border: none;-->
<!--        border-radius: 10em;-->
<!--        background: #f03699;-->
<!--        color: #fff;-->
<!--        font-family: 'Open Sans', sans-serif;-->
<!--        text-transform: uppercase;-->
<!--        font-weight: 600;-->
<!--        letter-spacing: 2px;-->
<!--        z-index: 1;-->
<!---->
<!--        transition: background-color 0.2s, color:0.2s;-->
<!--    }-->
<!---->
<!--    #login-form-submit:active{-->
<!--        background: #b52773;-->
<!--        color: #c9c9c9;-->
<!--    }-->
<!---->
<!--    p , a{-->
<!--        margin: 0;-->
<!--        padding: 0;-->
<!--    }-->
<!---->
<!--    a{-->
<!--        color: #898787;-->
<!--        font-size: 0.7em;-->
<!--        text-decoration: none;-->
<!--    }-->
<!---->
<!--    .hidden{-->
<!--        display: none;-->
<!--    }-->
<!---->
<!--    /*MEDIA QUERIES     */-->
<!---->
<!--    @media (max-height:800px) {-->
<!---->
<!--        body{-->
<!--            max-height: 100vh;-->
<!--        }-->
<!---->
<!--        .panel{-->
<!--            width: 450px;-->
<!--            max-width: 90%;-->
<!--            background-size: cover;-->
<!--            margin: 1% auto;-->
<!--        }-->
<!---->
<!--    }-->
<!---->
<!--    @media (max-width:500px) {-->
<!---->
<!--        html, body{-->
<!--            background:url(https://picsum.photos/3695/5543?image=827)  #fff;-->
<!--            background-repeat:no-repeat;-->
<!--            background-position: top center;-->
<!--            background-size: cover;-->
<!--            height: 100vh;-->
<!--            margin: 0px;-->
<!--            padding: 0px;-->
<!--            position: fixed;-->
<!--        }-->
<!---->
<!--        .panel{-->
<!--            background: none;-->
<!--            box-shadow: none;-->
<!--        }-->
<!---->
<!---->
<!--        form{-->
<!--            padding: 50px;-->
<!--        }-->
<!---->
<!--        .panel-switch{-->
<!--            margin-top: 30px;-->
<!--        }-->
<!---->
<!--        .panel-switch button{-->
<!--            display: inline-block;-->
<!--            width: 80px;-->
<!--            margin: 0px 10px 50px;-->
<!--            font-weight: 600;-->
<!--            font-size: 0.7em;-->
<!--        }-->
<!---->
<!--        form h1{-->
<!--            font-size: 1.5em;-->
<!--        }-->
<!---->
<!--        .login_form{-->
<!--            bottom:0;-->
<!--            width: 70%;-->
<!--            margin-top: 100px;-->
<!--        }-->
<!---->
<!--    }-->
<!--</style>-->
<!--<script>-->
<!--    $(document).ready(function(){-->
<!---->
<!--//--------- change color value of the form text/password inputs ------->
<!---->
<!--        const textInputs =  $("input[type='textbox']");-->
<!--        const passwordsInputs =  $("input[type='password']");-->
<!--        //--------- Login screen swicth ------->
<!---->
<!--        $("button").click(function(event){  //  prevent buttons in form to reload-->
<!--            event.preventDefault();-->
<!--        });-->
<!---->
<!--        $("a").click(function(event){  //  prevent 'a' links in form to reload-->
<!--            event.preventDefault();-->
<!--        });-->
<!---->
<!--        $("#sign_up").click(function(){ // when click Sign Up button, hide the Log In elements, and display the Sign Up elements-->
<!--            $("#title-login").toggleClass("hidden",true);-->
<!--            $("#login-fieldset").toggleClass("hidden",true);-->
<!--            $("#login-form-submit").toggleClass("hidden",true);-->
<!--            $("#lost-password-link").toggleClass("hidden",true);-->
<!--            $("#sign_up").toggleClass("active-button",false);-->
<!--            $("#log_in").removeAttr("disabled");-->
<!---->
<!--            $("#title-signup").toggleClass("hidden",false);-->
<!--            $("#signup-fieldset").toggleClass("hidden",false);-->
<!--            $("#signup-form-submit").toggleClass("hidden",false);-->
<!--            $("#log_in").toggleClass("active-button",true);-->
<!--            $("#sign_up").prop('disabled', true);-->
<!--        });-->
<!---->
<!--        $("#log_in").click(function(){ // when click Log In button, hide the Sign Up elements, and display the Log In elements-->
<!--            $("#title-login").toggleClass("hidden",false);-->
<!--            $("#login-fieldset").toggleClass("hidden",false);-->
<!--            $("#login-form-submit").toggleClass("hidden",false);-->
<!--            $("#lost-password-link").toggleClass("hidden",false);-->
<!--            $("#sign_up").toggleClass("active-button",true);-->
<!--            $("#log_in").prop('disabled', true);-->
<!---->
<!--            $("#title-signup").toggleClass("hidden",true);-->
<!--            $("#signup-fieldset").toggleClass("hidden",true);-->
<!--            $("#signup-form-submit").toggleClass("hidden",true);-->
<!--            $("#log_in").toggleClass("active-button",false);-->
<!--            $("#sign_up").removeAttr("disabled");-->
<!---->
<!--        });-->
<!--    });-->
<!---->
<!--</script>-->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">

<body>
<div class="container">
    <div class="row main">
        <div class="main-login main-center">
            <h2>Sign Up</h2>
            <form class="" method="post" action="#">

                <div class="form-group">
                    <label for="name" class="cols-sm-2 control-label">Your Name</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user-plus fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="name" id="name"  placeholder="Enter your Name" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="username" class="cols-sm-2 control-label">Username</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="username" id="username"  placeholder="Enter your Username" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="email" class="cols-sm-2 control-label">Your Email</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
                            <input type="text" class="form-control" name="email" id="email"  placeholder="Enter your Email" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="cols-sm-2 control-label">Password</label>
                    <div class="cols-sm-10">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
                            <input type="password" class="form-control" name="password" id="password"  placeholder="Enter your Password" required/>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <input type="submit" name="signupBtn" class="btn btn-success btn-lg btn-block login-button" value="Sign up">
                </div>
                <div id="register-link" class="text-right">
                    <a href="/loginController.php" class="text-info">Login Here</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>


<style type="text/css">
    body{
        height: 100%;
        background-repeat: no-repeat;
        background-image: url('/images/background.png');
        font-family: 'Oxygen', sans-serif;
        background-size: cover;
    }

    .main{
        margin:10px 15px;

    }

    .form-group{
        margin-bottom: 15px;
    }

    label{
        margin-bottom: 15px;
    }

    input,
    input::-webkit-input-placeholder {
        font-size: 11px;
        padding-top: 3px;
    }

    .main-login{
        background-color: #fff;
        /* shadows and rounded borders */
        -moz-border-radius: 2px;
        -webkit-border-radius: 2px;
        border-radius: 2px;
        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);

    }
    .form-control {
        height: auto!important;
        padding: 8px 12px !important;
    }
    .input-group {
        -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
        -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
        box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
    }
    #button {
        border: 1px solid #ccc;
        margin-top: 28px;
        padding: 6px 12px;
        color: #666;
        text-shadow: 0 1px #fff;
        cursor: pointer;
        -moz-border-radius: 3px 3px;
        -webkit-border-radius: 3px 3px;
        border-radius: 3px 3px;
        -moz-box-shadow: 0 1px #fff inset, 0 1px #ddd;
        -webkit-box-shadow: 0 1px #fff inset, 0 1px #ddd;
        box-shadow: 0 1px #fff inset, 0 1px #ddd;
        background: #f5f5f5;
        background: -moz-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #f5f5f5), color-stop(100%, #eeeeee));
        background: -webkit-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
        background: -o-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
        background: -ms-linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
        background: linear-gradient(top, #f5f5f5 0%, #eeeeee 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#f5f5f5', endColorstr='#eeeeee', GradientType=0);
    }
    .main-center{
        /*margin-top: 30px;*/
        margin: 0 auto;
        max-width: 400px;
        padding: 10px 40px;
        background: #136a8a;
        color: #FFF;
        text-shadow: none;
        -webkit-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
        -moz-box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
        box-shadow: 0px 3px 5px 0px rgba(0,0,0,0.31);
        background:
                -webkit-linear-gradient(to right, #267871, #136a8a);
        background:
                linear-gradient(to right, #267871, #136a8a);
        margin: auto;
        box-shadow:
                0px 2px 10px rgba(0,0,0,0.2),
                0px 10px 20px rgba(0,0,0,0.3),
                0px 30px 60px 1px rgba(0,0,0,0.5);
    }
    span.input-group-addon i {
        color: #136a8a;
        font-size: 17px;
    }

    .main-center .text-info{
        color: #FFFFFF;

    }

</style>

